name: Scheduled Python Script

on:
  schedule:
    - cron: '15 20 * * *' # Run every minute

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pandas matplotlib numpy pygsheets watchdog

      - name: Run Python script
        run: python main/src/LastTwentyOct4.py
