name: Scheduled Python Script

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Install the Python version needed

      - name: Setup venv
        run: python -m venv venv

      - name: Activate venv
        run: |
          source venv/Scripts/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python src/LastTwentyOct4.py

